### PR TITLE
enable 'crossSbtVersions' (0.13.16, 1.0.4)

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
cc: @alpinebuilder

**Comment by sullis** [comment]
cc: @jthompson6

**Comment by jthompson6** [comment]
Hi Sullis.

Thanks for your PR, but we are not maintaining this anymore. If you want to publish your own version, go ahead.

Best,
Jenny

**Comment by dbtsai** [comment]
+@chesterxgchen

@sullis I'm no longer with Alpine, so I don't have the access to this repo, and the right to publish the jars to artifacts. Should we  move this project to https://github.com/sbt ?

**Comment by jthompson6** [comment]
I do have credentials to publish to com.alpinenow, so I can do it if it's a one-time thing, but it's not a long term solution.

**Comment by dbtsai** [comment]
@sullis the build is failing, https://travis-ci.org/AlpineNow/junit_xml_listener/builds/311090615
and seems the it's because the sbt is pulling from alpine's internal repo. see https://github.com/AlpineNow/junit_xml_listener/blob/master/sbt#L140

Please fix it, and I think we're ready to merge it. Once it's merged, we can have help from @jthompson6 to publish it as one time thing. At the meantime, we can try to move it under sbt project.

**Comment by jthompson6** [comment]
@dbtsai this repo is probably going to be deleted soon, so you should fork it if you want to keep it.

**Comment by sullis** [comment]
obsolete

**Pull request closed without merging**
